Input
shivanigangadharan/style-ui pull request #11
Opened 2022-02-03 15:14 UTC by shivanigangadharan

Input component preview :- 

![image](https://user-images.githubusercontent.com/30795425/152370816-d5d21b94-b447-417d-afc2-515564ba9bdd.png)

Added standard, outlined, filled and their respective error validation styles.

2022-02-04 10:56 UTC, SanjayJatti commented on pages/docs/docs.css
> +    max-height: 400px;
use max-width: 100% to carbon container. That will make it responsive.

2022-02-04 11:01 UTC, SanjayJatti approved these changes
Overall code is clean and easily readable. You can add other types of forms or inputs. e.g radio button, checkbox, etc,

2022-02-04 11:01 UTC, SanjayJatti commented on components/input.css
> +    gap: 20px;
You can use rem unit instead of px for gap

2022-02-04 16:07 UTC, ashishnnnnn approved these changes
Code seems pretty much structured :+1:

2022-02-04 18:52 UTC, Prabhav-Sharma requested changes

2022-02-04 18:52 UTC, Prabhav-Sharma commented on components/input.css
> +    padding: 0.9rem 1rem;
You might want to define global variables in the style-guide to maintain consistency for example 
--space-small:1rem;
--space-xsmall:0.5rem;

2022-02-05 06:44 UTC, shivanigangadharan commented on components/input.css
> +    padding: 0.9rem 1rem;
Done in commit [324f664](https://github.com/shivanigangadharan/style-ui/pull/11/commits/324f664b12767699c2b4c44ec4583acd5636d9a9).

2022-02-05 06:55 UTC, Prabhav-Sharma approved these changes

2022-02-05 09:03 UTC, shivanigangadharan commented on components/input.css
> +    gap: 20px;
Done in commit [e1a563d](https://github.com/shivanigangadharan/style-ui/pull/11/commits/e1a563d2944056196bd10e35c673ca2516f6f1e0)

2022-02-05 09:05 UTC, shivanigangadharan commented on pages/docs/docs.css
> +    max-height: 400px;
Done in commit [ed0510f](https://github.com/shivanigangadharan/style-ui/pull/11/commits/ed0510fa2ff5d7517f3235adee07843c34c2b2c8)

2022-02-05 09:11 UTC, merged