added alert component
shivanigangadharan/style-ui pull request #6
Opened 2022-02-02 12:46 UTC by shivanigangadharan

Preview :- 

![image](https://user-images.githubusercontent.com/30795425/152156426-7145fbea-b175-4227-8e43-7145f83c3f89.png)

Added four types of alerts - error, warning, info and success.

2022-02-02 14:57 UTC, devananth commented on components/alert.css
> +    color: darkred;
I would suggest you not to use color names directly , store the color hex code in a CSS variable and reuse it.

2022-02-02 15:15 UTC, shivanigangadharan commented on components/alert.css
> +    color: darkred;
Done, have added color variables in commit d752bae.

2022-02-02 15:20 UTC, devananth commented on components/alert.css
> +    color: darkred;
Code looks clean now , you can proceed

2022-02-02 17:32 UTC, KanekarSnehal requested changes

2022-02-02 17:32 UTC, KanekarSnehal commented on components/alert.css
> +    padding: 1rem 1.5rem 1rem 1.5rem;
you can use shorthand property here `padding : 1rem 1.5rem`

2022-02-02 17:35 UTC, Maianki approved these changes
Suggested some minor changes. Everything else looks good.

2022-02-02 17:35 UTC, Maianki commented on components/badge.css
> +    overflow: visible;
Overflow is by default visible. So setting it to visible is not required here.

2022-02-02 17:35 UTC, Maianki commented on pages/docs/docs.html
>              <br/>
Avoid using <br> tag . More on this here https://stackoverflow.com/questions/1726073/is-it-sometimes-bad-to-use-br#:~:text=Generally%2C%20is,See%20Bed%20and%20BReakfast.

2022-02-02 17:35 UTC, Maianki commented on pages/docs/docs.html
>                  <text class="subtext"> A card has multiple layouts and you can specify different class names in order to use different layouts.</text>
Semantically try using ```<p> ```tag for text content. ```For e.g``` here it will be difficult for screen readers to figure out card is title and subtext is normal text.

2022-02-05 06:17 UTC, shivanigangadharan commented on components/alert.css
> +    padding: 1rem 1.5rem 1rem 1.5rem;
> you can use shorthand property here `padding : 1rem 1.5rem`

Done in commit [7ce27ae](https://github.com/shivanigangadharan/style-ui/pull/6/commits/7ce27ae11c67622a61739be24caf5abf482983af). Please approve if it seems fine now, thanks.

2022-02-05 06:22 UTC, shivanigangadharan commented on pages/docs/docs.html
>              <br/>
> Avoid using `<br>` tag . `More on this here` https://stackoverflow.com/questions/1726073/is-it-sometimes-bad-to-use-br#:~:text=Generally%2C%20is,See%20Bed%20and%20BReakfast.

Right, I'll be removing that in the 'menu' branch when I work on that.

2022-02-05 06:22 UTC, shivanigangadharan commented on pages/docs/docs.html
>                  <text class="subtext"> A card has multiple layouts and you can specify different class names in order to use different layouts.</text>
> Semantically try using `<p>, <h1>, <h2>`tag for text content. `For e.g` here it will be difficult for screen readers to figure out card is title and subtext is normal text.

Understood, will make this change in the 'card' branch. Thanks.

2022-02-05 06:33 UTC, KanekarSnehal approved these changes

2022-02-05 06:33 UTC, KanekarSnehal approved these changes

2022-02-05 06:40 UTC, KanekarSnehal approved these changes

2022-02-05 06:48 UTC, merged